name: Tests

on:
  workflow_dispatch: # Activate this workflow manually
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  tests:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.10"

      - name: Install Hatch
        run: pip install -U hatch
    
      - name: Ruff check
        run: hatch run fmt-check

      - name: Run
        run: hatch run test
